### ISSUE TITLE
Feature Request: Default Caching

### ISSUE THREAD

**Issue by wSedlacek** [gperdomor/nx-tools#10]
It would be awesome if a default value could be added to `cache_froms` to cache builds.
Additionally it would be great if `DOCKER_BUILDKIT=1` was added to the env and `BUILDKIT_INLINE_CACHE=1` was added to the build args.

See https://testdriven.io/blog/faster-ci-builds-with-docker-cache/ for more details

**Comment by gperdomor** [comment]
Solved in #15  👍
