### ISSUE TITLE
Feature request: allow setting SBOM options to container builder

### ISSUE THREAD

**Issue by sambonbonne** [gperdomor/nx-tools#1016]
Hello,

Some tools allow generating SBOM while building: `docker buildx` has a [`--sbom` argument](https://docs.docker.com/reference/cli/docker/buildx/build/#sbom) and `podman build` [has it and some more](https://docs.podman.io/en/stable/markdown/podman-build.1.html#sbom-preset) too (I didn't find the option in Kaniko).

It would be nice to be able to set the `--sbom` parameter in the `options` configuration, for example:

```json
{
  "container": {
    "executor": "@nx-tools/nx-container:build",
    "options": {
      "engine": "docker",
      "file": "path/to/Dockerfile",
      "sbom": "true",
      "metadata": {
        "images": [
          "my.registry.com/workspace/image"
        ],
        "load": true
      }
    }
  }
}
```

Note: in the example, I set the `--sbom` argument to `true` to simplify but it can be a string with more configuration.

Do you think it may be possible to add this argument, despite the fact that the option is different on Docker and Podman and even absent in Kaniko ?

**Comment by gperdomor** [comment]
@sambonbonne the option was added in version 5.3.0 only for docker engine... I hope that solve your issue 🙏🏻

**Comment by sambonbonne** [comment]
That was quick! Thanks for this!
