### ISSUE TITLE
Incorrect Setup Documentation

### ISSUE THREAD

**Issue by eflo11** [gperdomor/nx-tools#1046]
With the new version of 6.0.0 you no longer have an init command within the generators as you are getting ready to set up. Yet the documentation still has you putting the init command in place.

Current Documentation:
![image](https://github.com/gperdomor/nx-tools/assets/6474512/e131dec3-ba4b-466b-9d1f-e2065f2468ea)

PR Change from 6.0.0:
![image](https://github.com/gperdomor/nx-tools/assets/6474512/c8e6a87e-5827-4541-9223-0046b3703477)

**Comment by gperdomor** [comment]
@eflo11 thank you... it's fixed now
