### ISSUE TITLE
@nx-tools/nx-graphql-codegen:init Cannot find generator 'init'

### ISSUE THREAD

**Issue by AttonMor** [gperdomor/nx-tools#1062]
executing the nx g @nx-tools/nx-graphql-codegen:init command results in an error

 NX   Unable to resolve @nx-tools/nx-graphql-codegen:init.

Cannot find generator 'init' in /home/moraa/Documents/projects/erist/node_modules/@nx-tools/nx-graphql-codegen/generators.json.

Error: Unable to resolve @nx-tools/nx-graphql-codegen:init.
Cannot find generator 'init' in /home/moraa/Documents/projects/erist/node_modules/@nx-tools/nx-graphql-codegen/generators.json.
    at getGeneratorInformation (/home/moraa/Documents/projects/erist/node_modules/nx/src/command-line/generate/generator-utils.js:39:15)
    at /home/moraa/Documents/projects/erist/node_modules/nx/src/command-line/generate/generate.js:218:248
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/home/moraa/Documents/projects/erist/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/home/moraa/Documents/projects/erist/node_modules/nx/src/command-line/generate/command-object.js:13:22)

Node   : 22.2.0
OS     : linux-x64
yarn   : 1.22.22

nx                 : 19.1.1
@nx/js             : 19.1.1
@nx/jest           : 19.2.2
@nx/linter         : 19.1.1
@nx/eslint         : 19.1.1
@nx/workspace      : 19.1.1
@nx/cypress        : 19.1.1
@nx/devkit         : 19.1.1
@nx/eslint-plugin  : 19.1.1
@nx/nest           : 19.1.1
@nx/next           : 19.1.1
@nx/node           : 19.1.1
@nx/react          : 19.1.1
@nrwl/tao          : 19.1.1
@nx/web            : 19.1.1
@nx/webpack        : 19.1.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/next/plugin
@nx/cypress/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc           : 1.1.25
@nx-tools/nx-graphql-codegen : 1.0.1
---------------------------------------

**Comment by gperdomor** [comment]
@AttonMor sorry, there is an error in the readme, use `configuration` instead `init` generator...
`nx g @nx-tools/nx-graphql-codegen:configuration appName`... The readme it's fixed now

**Comment by Tyguy7** [comment]
` NX   [FAILED] Invalid Custom Plugin "typescript" `
