### ISSUE TITLE
question: Is there an easy way to define that additional files need to be included in dist 

### ISSUE THREAD

**Issue by Arjanno** [gperdomor/nx-tools#1086]
My specific question is around the ability to include default.conf for Nginx to the build output folder so dockerfile can copy it to right location.

**Comment by gperdomor** [comment]
@Arjanno You should be able to copy any file from the workspace, there is not need to include additional files in the dist folder... In any case, that is not related to the plugin, to include something else to the list folder you should check the documentation of the building tool used in your app (webpack, vite, rollup, etc)
