### ISSUE TITLE
[@nx-tools/nx-container] Add configuration for compact/silent logs

### ISSUE THREAD

**Issue by avaly** [gperdomor/nx-tools#1099]
The current behavior of the `@nx-tools/nx-container` plugin is to output a lot of noisy logs. For a simple docker build, there are ~200 lines of output, excluding the actual Docker build steps.

The existing `quiet` input option only hides the engine info.

There should be more control on the amount of logs printed.

**Comment by gperdomor** [comment]
@avaly please try with nx-container 6.0.2-alpha.2 and let me know... The version it's based on changes from #1114

**Comment by avaly** [comment]
The 6.0.2 version silences a lot of logs. However there's still 3 sections printed after the Docker build logs: `ImageID`, `Digest` & `Metadata`. Can we silence those as well?
