### ISSUE TITLE
Feature Request: Additional Builders/Schematics - Prisma

### ISSUE THREAD

**Issue by wSedlacek** [gperdomor/nx-tools#11]
[Prisma 2](https://www.prisma.io/) is an exciting new technology that has several CLI commands that would be nice to move to an NX Builder to bring it more in line with the Nx Monorepo philosophy.

The builder commands that would be useful are:
- `prisma generate`
- `prisma migrate save`
- `prisma migrate up`
- `prisma migrate down`

There are several options for these commands including the location of the schema file, the path toe the `env` file, create a new database if one doesn't exist, etc.

Additional options like the name of a migration etc can be command line args rather then schema args.

Additionally schematics to add Prisma to a NX Monorepo would be fantastic.

**Comment by gperdomor** [comment]
@wSedlacek Sure, why not? you can add a new plugin for that, maybe nx-prisma or something like that 👍

**Comment by wSedlacek** [comment]
Awesome! I will have something mocked up by the end of the week! Thank you!
