### ISSUE TITLE
Cannot find module '@swc/helpers/_/_interop_require_wildcard'

### ISSUE THREAD

**Issue by firebull81** [gperdomor/nx-tools#1116]
NX   Cannot find module '@swc/helpers/_/_interop_require_wildcard'
  
  Require stack:
  - /home/runner/work/.../.../node_modules/@nx-tools/nx-container/src/executors/build/executor.js
  - /home/runner/work/.../.../node_modules/nx/src/config/schema-utils.js
  - /home/runner/work/.../.../node_modules/nx/src/command-line/run/executor-utils.js
  - /home/runner/work/.../.../node_modules/nx/src/devkit-internals.js
  - /home/runner/work/.../.../node_modules/nx/src/utils/assert-workspace-validity.js
  - /home/runner/work/.../.../node_modules/nx/src/project-graph/build-project-graph.js
  - /home/runner/work/.../.../node_modules/nx/src/project-graph/project-graph.js
  - /home/runner/work/.../.../node_modules/nx/src/project-graph/file-utils.js
  - /home/runner/work/.../.../node_modules/nx/src/utils/package-manager.js
  - /home/runner/work/.../.../node_modules/nx/src/utils/package-json.js
  - /home/runner/work/.../.../node_modules/nx/src/utils/print-help.js
  - /home/runner/work/.../.../node_modules/nx/src/command-line/run/run.js
  - /home/runner/work/.../.../node_modules/nx/bin/run-executor.js

"nx": "19.6.1",
"@nx-tools/container-metadata": "6.0.2",
"@nx-tools/nx-container": "6.0.2",

node: v20.16.0
npm: 10.8.1

**Comment by gperdomor** [comment]
@firebull81 please can you provide a minimum reproducible repository?

**Comment by firebull81** [comment]
@gperdomor, it's obsolated already. Thank you.
