### ISSUE TITLE
Broken doc link on npm

### ISSUE THREAD

**Issue by vicb** [gperdomor/nx-tools#1117]
On https://www.npmjs.com/package/@nx-tools/nx-container,

"Multi-platform image" links to https://github.com/gperdomor/nx-tools/blob/HEAD/docs/advanced/multi-platform.md which is 404.

Do you have any idea why this can be?

Happy to submit a PR when  I understand the root cause.

Thanks for the helpful plugin!

**Comment by WTPOptAxe** [comment]
The CI links are also broken. I believe https://github.com/gperdomor/nx-tools/pull/1147 fixes this.

**Comment by gperdomor** [comment]
Thank you both for raising the issue and do the fix... It's now merged and the readme is updated in npm registry ❤️
