### ISSUE TITLE
[nx-prisma] Add support for passing `--no-hints` option to the `prisma generate` command

### ISSUE THREAD

**Issue by yaronuliel** [gperdomor/nx-tools#1126]
Currently, when executing the `prisma-generate` nx command - it shows hints from `prisma` (hints are instructional *and promotional* messages from the prisma library/creators - [source code](https://github.com/prisma/prisma/blob/ff167282ec28fbacd59dd00ac8d30ed367ab1406/packages/cli/src/Generate.ts#L270))
While it may help users while in development environment, having this promotional messages appear in CI/CD logs while building for production is super annoying.

This messages can be turned off by passing the flag `--no-hints` to the `prisma generate` command

Currently the `nx-prisma` plugin supports only `--watch` and `--data-proxy` flags, instead of supporting all the available flags/options that prisma provides

I've also posted a PR (#1125) to fix that

**Comment by gperdomor** [comment]
@yaronuliel thank you for your contribution... It's merged now and will be included in the next release
