### ISSUE TITLE
[nx-container] Wrap Docker output in a group

### ISSUE THREAD

**Issue by avaly** [gperdomor/nx-tools#1139]
When running this command in Github Actions, all the logs except the Docker command & output are wrapped in collapsible areas (groups). The Docker command & output are sometimes large & noisy (especially if using a remote registry cache - `cache-from` / `cache-to`). I think these should also be wrapped in a group.

**Comment by gperdomor** [comment]
@avaly I have no control about the output of docker build commands, there is nothing to do from our side :(
