### ISSUE TITLE
Feature Request: Core library for common code 

### ISSUE THREAD

**Issue by wSedlacek** [gperdomor/nx-tools#18]
From #16 
> One other change I considered was moving the utilities to @gperdomor/utils so that they could be shared between each library, however I wanted to check with you before making such a change.

This issue is to discuss a common library to be shared across builder/schematic libraries and determine what such a library should look like, include and what benefits it might offer.

**Comment by wSedlacek** [comment]
The biggest shared code between the existing projects is the `process-utils` and `env-utils`.

I believe the interface for `createProcess` can be improved. I started a few improvements in `nx-prisma` to make the testing pass without outputs showing in the console.
The next major improvement for `nx-prisma` would be supporting stdin inputs while the builder is running so prompts from things like the Prisma CLI can be responded to.

Additionally in `nx-prisma` I implemented a `createPrismaBuilder()` as a factory to reduce repeated code in the builders.
A more generic `createCommandLineBuilder()` could be created to further reduce boiler plate and facilitate faster and more refined builds of command line tools in the future.

**Comment by gperdomor** [comment]
Hi @wSedlacek, I just made several changes to the project, I update to Nx 10.1.0 and to OSS preset...

As I said before, I like the idea of a `common/core` lib with utils, even when only apply to `process-utils` and `env-utils`, now we have two plugins, but later could have more, so this `core` will help to avoid duplicated code.

Also I changed the packages from @gperdomor/nx-* to @nx-tools/nx-* (not published yet)

**Comment by wSedlacek** [comment]
Fantastic! Would you like me to work on build out `@nx-tools/core` or would you like to do that while I focus more on `nx-prisma`?
