### ISSUE TITLE
Chore: Update approved-plugins.json

### ISSUE THREAD

**Issue by wSedlacek** [gperdomor/nx-tools#26]
Note: This is probably already planned however I am making an issue for it so that it is not forgotten.

As we are making some changes to release to the `@nx-tools` organization now we need to update the [approved-plugins.json](https://github.com/nrwl/nx/edit/master/community/approved-plugins.json) in the [nwrl/nx](https://github.com/nrwl/nx) repo to reflect these changes. 

Additionally `@nx-tools/nx-prisma` could be purposed here if we feel it is hitting it's MVP requirements.
Additionally a release for `@gperdomor/nx-docker` should be done to deprecate it and notify existing users of the change in package name.

**Comment by gperdomor** [comment]
Of course, @gperdomor/nx-docker is already deprecated, we can send a MR to reflect that change and include the nx-prisma too... I don't use prisma so I don't know what kind of features you wanna implement, but I think this is a good start for people who use it. IMO we can inform now about nx-prisma, but is your decision :D

**Comment by wSedlacek** [comment]
So in my projects I have found the current implementation of `nx-prisma` to do the basics of what I need.
For example in my [prisma generators](https://github.com/wSedlacek/prisma-generators) I use `nx-prisma` to work multiple projects that use prisma in my examples. By default with the Prisma CLI you would need to add an argument to specify what schema to use and most users would put that in their package.json if they need to use two regularly. I believe that the `workspace.json`/`angular.json` is a much better place for such configurations so `nx-prisma` allows me to do that.

There are definitely more features I would like to add to `nx-prisma` but I believe it is at MVP at this state and would be useful for other developers as well.

**Comment by gperdomor** [comment]
@wSedlacek Agree

**Comment by wSedlacek** [comment]
For documentation: https://github.com/nrwl/nx/pull/3652

**Comment by gperdomor** [comment]
Solved
