### ISSUE TITLE
Add versions to tags

### ISSUE THREAD

**Issue by DaSchTour** [gperdomor/nx-tools#279]
For me it's a bit unclear how the tags should be used. I have multiple docker targets in my workspace, so it's not possible to use env. I would like to have the possibility to define a pattern in the tags and provide this by env. An example for the metadata extraction would also be helpful, as I can't imagine from the description how this actually works.

**Comment by gperdomor** [comment]
An example of metadata extraction is in this [docs](https://github.com/gperdomor/nx-tools/tree/main/packages/nx-docker)
