### ISSUE TITLE
Support for environment variables in options has been removed

### ISSUE THREAD

**Issue by tfohlmeister** [gperdomor/nx-tools#315]
I see that in the recent 1.0.0 and 1.0.1 releases the support for environment variables using `sh -c` has been removed.
It was introduced as part of this ticket: https://github.com/gperdomor/nx-tools/issues/89 and removed here: https://github.com/gperdomor/nx-tools/commit/fafca23655da75152f7e03e06dd152f2b78bef1f#r52778259

I was relying on it and would love to know why it was removed and what to use instead.
Thanks!

**Comment by gperdomor** [comment]
Can you please provide a minimum reproduction repository?

**Comment by gperdomor** [comment]
@tfohlmeister try with 1.0.2 😄

**Comment by tfohlmeister** [comment]
Thanks, this is it! Works again in 1.0.2!
