### ISSUE TITLE
Issue(nx-docker): Incorrect documentation and JSON schema of input options

### ISSUE THREAD

**Issue by miluoshi** [gperdomor/nx-tools#330]
[Readme](https://github.com/gperdomor/nx-tools/tree/main/packages/nx-docker#customizing) of nx-docker package incorrectly documents input options. Option `build-args` is not working. The correct one is `buildArgs` ([src](https://github.com/gperdomor/nx-tools/blob/main/packages/nx-docker/src/executors/build/context.ts#L62)).
Similarly, the `@nx-tools/nx-docker:build` executor's [schema.json](https://github.com/gperdomor/nx-tools/blob/main/packages/nx-docker/src/executors/build/schema.json#L19) incorrectly documents it.

**Comment by jshaw-cm** [comment]
@miluoshi Good catch, just saved me some time.

**Comment by gperdomor** [comment]
@miluoshi @jshaw-cm please try with the `1.1.0-alpha.3`, which fix the schema problem

**Comment by miluoshi** [comment]
> @miluoshi @jshaw-cm please try with the `1.1.0-alpha.3`, which fix the schema problem

Looks good, thanks! 👍
