### ISSUE TITLE
none:none docker image tag created

### ISSUE THREAD

**Issue by KamalAman** [gperdomor/nx-tools#382]
I am using the the following NX workspace.json configuration 

```
"docker": {
    "builder": "@nx-tools/nx-docker:build",
    "options": {
      "metadata": {
        "images": ["org/image],
        "tags": [
          "latest",
          "type=sha"
        ]
      }
    }
  }
```

I get 3 images tags cerated latest, sha, and none

The none image tag should not be created.

**Comment by gperdomor** [comment]
Hi @KamalAman... 

The "latest" item in tags array is the problem, please check [this](https://github.com/docker/metadata-action#tags-input) for valid values...

If you want a org/image:latest tag you need to use the [flavor](https://github.com/docker/metadata-action#flavor-input) config

**Comment by KamalAman** [comment]
Thanks, that makes sense.
