### ISSUE TITLE
Looser tslib dependency

### ISSUE THREAD

**Issue by wSedlacek** [gperdomor/nx-tools#385]
https://github.com/gperdomor/nx-tools/blob/756aefe933bd9711c1062f9094d6bf9fe04b9399/packages/nx-docker/package.json#L22

RxJS is still using tslib `~2.1.0`, it would be nice to match that version.

**Comment by gperdomor** [comment]
@wSedlacek in fact I think I can remove that dependency 🤔 ...

Did you have an issue related to this?

**Comment by wSedlacek** [comment]
It didn't cause any errors, however due to the version conflict I had two versions of tslib installed in my project.
Not a big deal, but it would be nice to have versions matching

Here is the issue on the rxjs side
https://github.com/ReactiveX/rxjs/issues/6689

**Comment by wSedlacek** [comment]
> @wSedlacek in fact I think I can remove that dependency 🤔 ...

Before you remove it I would recommend checking to see that you have the `importHelpers` configured such that your compiled code does not require `tslib`.

https://www.typescriptlang.org/tsconfig#importHelpers
https://github.com/gperdomor/nx-tools/blob/ca1949c9a4cab9714a6344590baf2fef144bdf6c/tsconfig.base.json#L10

From what I understand TypeScript 4.4 does need tslib 2.3.0+ (See the issue that was closed on ng-packgr)

**Comment by gperdomor** [comment]
I set all packages to use ^2.1.0

**Comment by gperdomor** [comment]
I will close this now... 😄

**Comment by wSedlacek** [comment]
Thank you!
