### ISSUE TITLE
Any way to use docker digest in subsequent steps?

### ISSUE THREAD

**Issue by patrickmichalina** [gperdomor/nx-tools#389]
I cannot seem to figure out how to capture the digest of the docker image. The tooling is working great but I need the digest to perform a release and unable to capture in github actions. Any tips here?

**Comment by nhuray** [comment]
I have the same needs. 

I would like to create a `deploy` executor picking the image tag computed (using docker metadata) by the `nx-docker` executor.

Not sure how I can achieve that. Any tips ?

**Comment by gperdomor** [comment]
Hi @patrickmichalina, @nhuray ... Thank you for using this plugin, latest version of the plugin `@nx-tools/nx-container` 4.0.0 creates a `.nx-container` folder with that output, so you can read from that folder.

From today this new plugin replaces the old `@nx-tools/nx-docker` plugin

**Comment by david1542** [comment]
I also have this issue and I cannot find any `.nx-container` in my folder. Is there a documentation somewhere?

**Comment by gperdomor** [comment]
@david1542 hi, the folder is inside `node_modules/.cache` folder 😄

**Comment by t3chguy** [comment]
It'd be nice to be able to influence this path using an envvar https://github.com/gperdomor/oss/blob/main/packages/nx-container/src/executors/build/context.ts#L141 instead of using a `.cache` directory for output
