### ISSUE TITLE
NX 13.5.3 breaks nx-docker on GHA

### ISSUE THREAD

**Issue by roderik** [gperdomor/nx-tools#424]
After upgrading from NX 13.5.1 to 13.5.3 we started getting this error on GHA

```
>  Nx Docker  Docker info

/usr/bin/docker version
node:buffer:1053
    return this.utf8Write(string, 0, this.length);
                ^

TypeError: argument must be a string
    at Buffer.write (node:buffer:1053:17)
    at Socket.process.stdout._write (/home/runner/work/bpaas-smartcontractsets/bpaas-smartcontractsets/node_modules/@nrwl/cli/lib/run-cli.js:43:20)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Socket.<anonymous> (/home/runner/work/bpaas-smartcontractsets/bpaas-smartcontractsets/node_modules/@actions/exec/lib/toolrunner.js:421:54)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
node:buffer:1053
    return this.utf8Write(string, 0, this.length);
```

downgrading back solved it, but somewhere something changed

**Comment by JWood48** [comment]
Also an issue on 13.6.1

**Comment by DaSchTour** [comment]
It's also an issue with Jenkins. Any ideas where/why this is happening?

**Comment by gperdomor** [comment]
Mmmm... that's weird, try with the latest version of nx and take a look to this repository: https://github.com/gperdomor/nx-docker-sandbox where it's working fine

**Comment by DaSchTour** [comment]
Well my branch with version 1.1.0-alpha.3 works with nx 13.7.1
My branch where I tried to upgrade to nx-docker 2.2.0 failes with

```
error: tag is needed when pushing to registry
buildx failed with: error: tag is needed when pushing to registry
```

**Comment by gperdomor** [comment]
@DaSchTour did you update your config too? This should help https://github.com/gperdomor/nx-tools/blob/main/packages/nx-docker/UPGRADE.md

**Comment by roderik** [comment]
I would categorise the diff between v1 and v2 ad a different problem. We have been running v2 since before the stable releases, there is definitely no upgrade issue at play here

**Comment by roderik** [comment]
FYI, renovate just upgraded our repos to v13.7.1 of NX and everything built. So maybe it is solved. Nothing in the changelog stood out.

**Comment by DaSchTour** [comment]
> I would categorise the diff between v1 and v2 as a different problem. We have been running v2 since before the stable releases, there is definitely no upgrade issue at play here

Yeah, it's different but's also somehow related. There is also this issue that relates to this: https://github.com/gperdomor/nx-tools/issues/362

I have my v1.1 build running again with 13.7.1. Have to verify if there is any possibility to get v2 working.

**Comment by MkMan** [comment]
I don't use `nx-tools` but I am also having this error when running Jest tests locally with Nx version 13.6.1.

**Comment by DaSchTour** [comment]
@MkMan try with 13.7.1

**Comment by MkMan** [comment]
> @MkMan try with 13.7.1

That worked. Thanks @DaSchTour
