### ISSUE TITLE
nx-docker: can't import module after moving to swc

### ISSUE THREAD

**Issue by andersonba** [gperdomor/nx-tools#561]
Hi! After upgrading to version 3.0.0, my custom executor that runs `nx-docker` internally was broken:

My code:
```typescript
import { run } from '@nx-tools/nx-docker'
```

Error:
```
(0 , _nxDocker).run is not a function
```

Debugging:
```
import { run } from '@nx-tools/nx-docker'
console.log(run)
> { run: [AsyncFunction: run], default: [AsyncFunction: run] }
```

**Comment by gperdomor** [comment]
Mmmm... Yeah something weird happening with swc 🤔 ... But I was able to run using

```
const { run } = require("@nx-tools/nx-docker");

run.run({...});
```

Try with that :D

**Comment by andersonba** [comment]
haha yeah, that was my hotfix.. however, I had to bypass the typescript

<img width="999" alt="image" src="https://user-images.githubusercontent.com/1501013/174462623-46c634b9-16d2-4ba1-afbc-40a2948cc917.png">
