### ISSUE TITLE
Package Managers Support

### ISSUE THREAD

**Issue by exsesx** [gperdomor/nx-tools#598]
I've discovered that when I'm using `pnpm nx my-service:generate`, the process fails with the following error: `The process '/usr/local/bin/npx' failed with exit code 1`.

The original command: `npx prisma generate --schema=...`

Is there any way to configure the package manager? For example, use `pnpx` instead of `npx` or something?

My nx.json has the following CLI options:

```json
"cli": {
    "packageManager": "pnpm"
},
```

I believe this issue lies here:
https://github.com/gperdomor/nx-tools/blob/cb6a268c44a615f5044478ede7cd69dabd0b73e3/packages/nx-prisma/src/executors/generate/executor.ts#L6

**Comment by gperdomor** [comment]
@exsesx handled in https://github.com/gperdomor/nx-tools/pull/630.. Can you try version `4.0.0-alpha.8` please?

**Comment by exsesx** [comment]
Now I get:

<img width="1551" alt="image" src="https://user-images.githubusercontent.com/20399517/198721664-b8c9c327-8b16-468b-8fa1-a3e3e07af532.png">

If I downgrade to 3.0.1 (my current version), everything works fine. 

Thanks for working on this, though.

**Comment by gperdomor** [comment]
@exsesx my bad, I forgot to mention that in v4 the working the working directory of the executor command is changed to the project folder so you need to change the schema from `apps/location-service/prisma/schema.prisma` to `prisma/schema.prisma` or just remove the option because that is the default file for prisma :D

**Comment by exsesx** [comment]
Okay, sure! 

It seems fixed to me, anyways. It runs pnpm now 👍🏻

Looking forward to the next major release going live.

**Comment by gperdomor** [comment]
@exsesx I will close this since v4 is now GA

**Comment by exsesx** [comment]
@gperdomor fantastic news. Thank you!
