### ISSUE TITLE
Better support for OCI containers

### ISSUE THREAD

**Issue by gperdomor** [gperdomor/nx-tools#603]
Currently nx-docker supports only docker, for the next version I want to explore the integration with other providers like Podman and Kaniko

**Comment by StringKe** [comment]
Very interested, I can help you test new content.

**Comment by gperdomor** [comment]
@StringKe 
The feature was added in https://github.com/gperdomor/nx-tools/pull/628... We need to improve docs before an official release but can be tested using the alpha versions...

Kaniko support was added too...

New docker images was released to use inside CI builds with those container engines:
https://hub.docker.com/r/gperdomor/nx-kaniko
https://hub.docker.com/r/gperdomor/nx-podman
