### ISSUE TITLE
Source Code of the Dockerfile

### ISSUE THREAD

**Issue by rmarku** [gperdomor/nx-tools#613]
The source code of the image  `docker pull ghcr.io/gperdomor/nx-docker:latest`  is not available on the repo.

Issue #587 has a response with the link https://github.com/gperdomor/nx-tools/issues/587#issuecomment-1183342947 but it's broken.

Is de source available?

**Comment by gperdomor** [comment]
Hi @rmarku, sorry for that but for the repo was made private during the V4 development, which now includes Podman and Kaniko builder too... You can sponsor this project with the second tier and get access to the source code of this three images:

1. https://hub.docker.com/r/gperdomor/nx-docker
2. https://hub.docker.com/r/gperdomor/nx-podman
3. https://hub.docker.com/r/gperdomor/nx-kaniko

In order to take advantage of this new builder please migrate from `@nx-tools/nx-docker` to `@nx-tools/nx-container` 😄

**Comment by ethanbrooks** [comment]
Hi @gperdomor I like the model you are using for mixed licence and I sponsored you on my personal card.. Will switch to a coperate one shortly. However the link you have attached to the sponsorship for the docker images is out of date.. https://github.com/whiteholeio/nx-container-builder

I have been working on adding support for nx-dotnet so will be switching from alpine to debian using mcr.microsoft.com/dotnet/sdk:6.0 as a base... 
After than will build profiles for @nrwl/angular with module federation and SSR.. Then @nxtensions/astro

Also happy to contribute back to .gitlab-ci.yml

Let me know if you are interested in PRs... 

Also where I can find the Dockerfile for [gperdomor/nx-docker](https://hub.docker.com/r/gperdomor/nx-docker)

Thanks for the cool nx plugin ;-).

> Hi @rmarku, sorry for that but for the repo was made private during the V4 development, which now includes Podman and Kaniko builder too... You can sponsor this project with the second tier and get access to the source code of this three images:
> 
> 1. https://hub.docker.com/r/gperdomor/nx-docker
> 2. https://hub.docker.com/r/gperdomor/nx-podman
> 3. https://hub.docker.com/r/gperdomor/nx-kaniko
> 
> In order to take advantage of this new builder please migrate from `@nx-tools/nx-docker` to `@nx-tools/nx-container` 😄

**Comment by ethanbrooks** [comment]
> Hi @gperdomor I like the model you are using for mixed licence and I sponsored you on my personal card.. Will switch to a coperate one shortly. However the link you have attached to the sponsorship for the docker images is out of date.. https://github.com/whiteholeio/nx-container-builder
> 
> I have been working on adding support for nx-dotnet so will be switching from alpine to debian using mcr.microsoft.com/dotnet/sdk:6.0 as a base... After than will build profiles for @nrwl/angular with module federation and SSR.. Then @nxtensions/astro
> 
> Also happy to contribute back to .gitlab-ci.yml
> 
> Let me know if you are interested in PRs...
> 
> Also where I can find the Dockerfile for [gperdomor/nx-docker](https://hub.docker.com/r/gperdomor/nx-docker)
> 
> Thanks for the cool nx plugin ;-).
> 
> > Hi @rmarku, sorry for that but for the repo was made private during the V4 development, which now includes Podman and Kaniko builder too... You can sponsor this project with the second tier and get access to the source code of this three images:
> > 
> > 1. https://hub.docker.com/r/gperdomor/nx-docker
> > 2. https://hub.docker.com/r/gperdomor/nx-podman
> > 3. https://hub.docker.com/r/gperdomor/nx-kaniko
> > 
> > In order to take advantage of this new builder please migrate from `@nx-tools/nx-docker` to `@nx-tools/nx-container` 😄

Sorry by bad.. I guess there is some async time getting added to https://github.com/whiteholeio/nx-container-builder

I am in now.. Quite interesting approch to multi arch.. 

Note to anyone who reads this... it is worth paying for look...

**Comment by gperdomor** [comment]
Hi @ethanbrooks, thank you very much for your support, I'm glad to hear your feedback... As promised in the sponsorship tiers, I will update the readme to include you name as sponsor
