### ISSUE TITLE
Nodejs < 16.x isn't really supported

### ISSUE THREAD

**Issue by yitzchak-ben-ezra-ecoplant** [gperdomor/nx-tools#614]
We're using Node 14.x
trying to use the docker extension we're getting this error:
```
>  NX   Cannot find module 'node:crypto'

   Require stack:
   - C:\gitWorkspace\github\monorepo\nx\node_modules\.pnpm\@nx-tools+nx-docker@3.0.3_r36dwqzm7gxuzkgyg2vz4dr7pa\node_modules\@nx-tools\nx-docker\src\executors\build\executor.js
   - C:\gitWorkspace\github\monorepo\nx\node_modules\.pnpm\nx@14.6.5\node_modules\nx\src\config\workspaces.js      
   - C:\gitWorkspace\github\monorepo\nx\node_modules\.pnpm\nx@14.6.5\node_modules\nx\src\command-line\run.js       
   - C:\gitWorkspace\github\monorepo\nx\node_modules\.pnpm\nx@14.6.5\node_modules\nx\bin\run-executor.js
```

I went to the file `executor.js` and changed these lines:
```js
const _nodeCrypto = require("node:crypto");
const _promises = require("node:fs/promises");
const _nodePath = require("node:path");
```

to this:
```js
const _nodeCrypto = require("crypto");
const _promises = require("fs/promises");
const _nodePath = require("path");
```

now everything works - but it was just a local workaround, not really helping me.

you can see in the docs that `require` syntax was changed starting from node 16.x to be `require(node:crypto)` instead of `require(crypto)` in node 14.x

I saw in your `package.json` that this extension is defined to support node 14, but I think it's not really working:
```json
"engines": {
    "node": ">=14"
  },
```

Am I missing anything?
do you have a solution for me? or I must upgrade my node version?

**Comment by gperdomor** [comment]
@yitzchak-ben-ezra-ecoplant please update to 3.0.4 and let me know 👍🏻

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
@gperdomor I don't know how you fixed it so quick! but it works!! 🏆🏆🏆

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
@gperdomor is it going to work on future versions too?
I can't see any code changes in the repo - or a PR waiting to get merged

**Comment by gperdomor** [comment]
I did the changes over the latest tag 😄... yes it will work in future versions too after I made the changes on the main branch
