### ISSUE TITLE
Feature Request(nx-docker): disable Docker info

### ISSUE THREAD

**Issue by Djiit** [gperdomor/nx-tools#621]
Hey,

Is it possible to add a `quiet` option to avoid displaying the version/info logs each time ?

Thanks

**Comment by gperdomor** [comment]
@Djiit yes I can do that, I will include in the next v4 release :)

**Comment by gperdomor** [comment]
Hi @Djiit, please migrate to `@nx-tools/nx-container` 4.0.0 and use the `quiet` option or `INPUT_QUIET` environment variable...
