### ISSUE TITLE
nx-prisma: custom env variable path

### ISSUE THREAD

**Issue by temarusanov** [gperdomor/nx-tools#643]
Hello, I want to import custom env path to my prisma schema, but it has no flags to set the env file. How can I do that?

```
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native", "linux-musl"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL") // <-- here
}
```

**Comment by gperdomor** [comment]
nx load a .env file from the project root or the project folder... But in any case this issue is related to [prisma](https://www.prisma.io/docs/guides/development-environment/environment-variables) project
