### ISSUE TITLE
Multiple INPUT_TAGS not working

### ISSUE THREAD

**Issue by dlip** [gperdomor/nx-tools#648]
It seems only `tag2` is pushed if i set something like `INPUT_TAGS=tag1,tag2` with

```
    "docker": {
      "executor": "@nx-tools/nx-container:build",
      "options": {
        "metadata": {
          "images": [
            "foobar.dkr.ecr.ap-southeast-2.amazonaws.com/myapp"
          ]
        }
      }
    }
```

**Comment by gperdomor** [comment]
Hi @dlip, if you want to get `foobar.dkr.ecr.ap-southeast-2.amazonaws.com/myapp:tag1` and `foobar.dkr.ecr.ap-southeast-2.amazonaws.com/myapp:tag2` you need to remove the `metadata` property and use `INPUT_TAGS=foobar.dkr.ecr.ap-southeast-2.amazonaws.com/myapp:tag1, foobar.dkr.ecr.ap-southeast-2.amazonaws.com/myapp:tag2`...

or update your project.json to:

```
"docker": {
  "executor": "@nx-tools/nx-container:build",
  "options": {
    "tags": [
      "foobar.dkr.ecr.ap-southeast-2.amazonaws.com/myapp:tag1",
      "foobar.dkr.ecr.ap-southeast-2.amazonaws.com/myapp:tag2"
    ]
  }
}
```

Using `metadata` in the executor options, enables other flow inside the plugin to set tags based on the CI/Git context... More info here: https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/docs/advanced/tags-labels.md

Also if you want to use metadata and override the tags using environment variables please check this https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/TROUBLESHOOTING.md#inline-execution

**Comment by dlip** [comment]
Thanks, that works well :+1:
