### ISSUE TITLE
nx-container does not interpolate build args

### ISSUE THREAD

**Issue by chromey** [gperdomor/nx-tools#652]
Hi,

with `nx-docker` it was possible to supply build args such as
```json
"build-args": ["ARG_NAME=$ENV_VAR"]
```
`nx-container` treats `$ENV_VAR` as a literal string and does not interpolate the environment variable. Was this a conscious decision? The migration guide does not mention this.

**Comment by gperdomor** [comment]
@chromey it's a bug... It's fixed in version 4.0.1 😄 

Thank you for report this issue 👍🏻
