### ISSUE TITLE
Clarification on what nx-container plugin does

### ISSUE THREAD

**Issue by maximveksler** [gperdomor/nx-tools#659]
Hey,

I'm looking for similar functionality as turbo's docker prune https://turbo.build/repo/docs/handbook/deploying-with-docker 

Does nx-container plugin offers similar approach? 

It would be great for some documentation on the problems this plguin solve.

Best 👍

**Comment by gperdomor** [comment]
@maximveksler This plugin is only to build container images of your affected applications using docker, podman or kaniko... The tagging could be manual or automatic based on git context (similar to `https://github.com/docker/build-push-action` and `https://github.com/docker/metadata-action`)...

You can check this [github sandbox](https://github.com/gperdomor/nx-container-sandbox) or [gitlab sandbox](https://gitlab.com/gperdomor/nx-container-sandbox)

**Comment by maximveksler** [comment]
Got it, thank you
