### ISSUE TITLE
Support TeamCity

### ISSUE THREAD

**Issue by ianldgs** [gperdomor/nx-tools#670]
TeamCity is not a supported CI provider.
The troubleshooting suggests using `CI_CONTEXT_FALLBACK_TO_LOCAL=true`, however TeamCity uses [git sparse-checkout](https://www.jetbrains.com/help/teamcity/git.html#Limitations).

That seemingly causes the "local git context" to fail on:
`git symbolic-ref HEAD`
```
 fatal: ref HEAD is not a symbolic ref
```

**Comment by gperdomor** [comment]
Hi @ianldgs... I don't use TeamCity so I don't know how it works and I din't found enough documentation about environment variables exposed in TC pipelines, if you can help me with that, will be great...

Also you can send a MR for this, take a look at this one for reference: https://github.com/gperdomor/nx-tools/pull/685/files

**Comment by ianldgs** [comment]
Hi @gperdomor!

I'm working on it. The only thing is that teamcity doesn't seem to have all the necessary information. Would it be acceptable to use the local git helpers when some property is not available?

**Comment by gperdomor** [comment]
Yes no problem
