### ISSUE TITLE
Docker build fails to install a library

### ISSUE THREAD

**Issue by fbloo** [gperdomor/nx-tools#736]
NX version: 15.4.2
@nx-tools/nx-container: 4.0.2

We are trying to build a container image for a NestJS app, however the build fails to install local packages/libraries. We are using the default generated Dockerfile. (The part below fails)
```
# Install dependencies only when needed
FROM docker.io/node:lts-alpine as deps
RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app
COPY dist/apps/myapp-api/package*.json ./
RUN npm install --only=production
```

Now consider the application `myapp-api` which tries to install our library`@myorg/event-types`. The NPM install fails with the following error:
```
#10 [deps 6/6] RUN npm install --only=production
#10 1.155 npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.
#10 32.22 npm WARN ERESOLVE overriding peer dependency
#10 32.22 npm WARN While resolving: myapp-api@undefined
#10 32.22 npm WARN Found: @myorg/event-types@undefined
#10 32.22 npm WARN node_modules/@myorg/event-types
#10 32.22 npm WARN   peer @myorg/event-types@"0.0.1" from the root project
#10 32.22 npm WARN
#10 32.22 npm WARN Could not resolve dependency:
#10 32.22 npm WARN peer @myorg/event-types@"0.0.1" from the root project
#10 40.98 npm notice
#10 40.99 npm notice New major version of npm available! 8.19.3 -> 9.4.0
#10 40.99 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.4.0>
#10 40.99 npm notice Run `npm install -g npm@9.4.0` to update!
#10 40.99 npm notice
#10 40.99 npm ERR! code E404
#10 40.99 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@myorg%2fevent-types - Not found
#10 40.99 npm ERR! 404
#10 40.99 npm ERR! 404  '@myorg/event-types@0.0.1' is not in this registry.
#10 40.99 npm ERR! 404
#10 40.99 npm ERR! 404 Note that you can also install from a
#10 40.99 npm ERR! 404 tarball, folder, http url, or git url.
#10 40.99
#10 40.99 npm ERR! A complete log of this run can be found in:
#10 40.99 npm ERR!     /root/.npm/_logs/2023-01-26T07_25_31_744Z-debug-0.log
#10 ERROR: executor failed running [/bin/sh -c npm install --only=production]: exit code: 1
```

It seems that it could find the package `@myorg/event-types@undefined` where the version is undefined but not the version 0.0.1 which is required.

- In the project.json we have enabled `"generatePackageJson": true`. In the package.json in the dist folder it lists `"@myorg/event-types": "0.0.1"`
- The package.json of our package lists `"version": "0.0.1",`
- I try to run `nx container myapp-api`

Am I missing something obvious here?

**Comment by gperdomor** [comment]
Hi @fbloo, seems like npm ins trying to install the package from the remote registry... This is not an issue from the plugin since the docker command is working, it's a problem related to the generated package.json, maybe your `@myorg/event-types` is a `publishable` lib and that's why nx is putting that in the package.json

**Comment by fbloo** [comment]
I've been experimenting a bit and I think it might be caused by the type of monorepo. When I try this in a integrated repo (instead of package based), it works like a charm. 

I noticed that the build step of the integrated repo will actually build the source code of libs with the app itself (with webpack). I'll look into how a can convert my repo.
