### ISSUE TITLE
NX Unsupported CI Provider

### ISSUE THREAD

**Issue by Divaaan** [gperdomor/nx-tools#790]
Hi @gperdomor 

So I've been trying to get the process of building it through podman and docker on Bitbucket by haven't managed to get it working. 
Per our architect he suggested I rather do it on AWS through CodeBuild as our deployed stuff also resides in AWS.
Setting up everything and using your `nx-docker` image with privileged permissions I don't get the error in my previous issue anymore (https://github.com/gperdomor/nx-tools/issues/789) but instead now getting the following error `NX Unsupported CI Provider`.

I'm not sure if this is related to your project or if it's an actual NX issue but I haven't managed to find anything online where someone has experienced the same issue.

If it's not part of your package I'll open an issue on the NX repo.

Thanks alot!

**Comment by Divaaan** [comment]
@gperdomor Okay so I found the code that throws the error. I see it is from your package where you set the context etc for the CI. I see you have almost a fallback for when it's not a CI and then has a fallback to local but can't seem to see if you can set it anywhere 🤔? Unless I manually set the environment variable ` CI_CONTEXT_FALLBACK_TO_LOCAL` on CodeBuild and then go from there. Not sure if that would maybe work?

**Comment by gperdomor** [comment]
This is solved in the next version `6.0.0`, feel free to use the current `6.0.0-alpha.3`
