### ISSUE TITLE
Does not appear to merge configurations correctly....

### ISSUE THREAD

**Issue by MHacker9404** [gperdomor/nx-tools#798]
Given this project.json:
`{
  "name": "nx-base",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/nx-base/src",
  "projectType": "application",
  "targets": {
    "container": {
      "executor": "@nx-tools/nx-container:build",
      "options": {
        "engine": "docker",
        "metadata": {
          "images": [
            "image-name"
          ],
          "push": true,
          "no-cache": true,
          "tags": [
            "nx-base",
            "type=schedule",
            "type=ref,event=branch",
            "type=ref,event=tag",
            "type=ref,event=pr",
            "type=sha,prefix=sha-"
          ]
        }
      },
      "configurations": {
        "lts": {
          "file": "apps/nx-base/Dockerfile.lts",
          "metadata": {
            "tags": [
              "lts"
            ]
          }
        },
        "current": {
          "file": "apps/nx-base/Dockerfile.current",
          "metadata": {
            "tags": [
              "current"
            ]
          }
        }
      }
    }
  },
  "tags": []
}
`
I would expect to generate images with a tag of `image-name:tag` based on the configuration - but I'm getting images without a name:tag.  I have to add the `images` property to the configurations metadata also?

**Comment by gperdomor** [comment]
Hi @MHacker9404 metadata config enables a flow for build tags based on CI or Git context, this flow runs when metadata.images is configured... If you want to tag your images manually just use the tags config outside metadata config, something like this:

```
{
  "container":{
    "executor":"@nx-tools/nx-container:build",
    "options":{
      "engine":"docker",
      "push":true,
      "no-cache":true,
    },
    "configurations":{
      "lts":{
        "file":"apps/nx-base/Dockerfile.lts",
        "tags": ["image-name:lts"]
      },
      "current":{
        "file":"apps/nx-base/Dockerfile.current",
        "tags": ["image-name:current"]
      }
    }
  }
}
```

I hope to this solve your issue, let me know if you need more help :D
