### ISSUE TITLE
Update devkit dependency for Nx 16

### ISSUE THREAD

**Issue by vicb** [gperdomor/nx-tools#801]
With nx 16.0.3, `nx report` reports:

```
   Node   : 18.16.0
   OS     : linux x64
   npm    : 9.5.1
   Hasher : Native
   
   nx (global)        : 16.1.0
   nx                 : 16.0.3
   [...]
   --------------------------------------
   Community plugins:
   @nx-tools/nx-container : 4.0.3
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@15.9.3
```

The `@nrwl/devkit@15.9.3` dependency is pulled by `nx-container`:

```
$ npm ls @nrwl/devkit
flyxc@2.0.0 /usr/local/google/home/berchet/code/flyxc
├─┬ @nx-tools/nx-container@4.0.3
│ ├── @nrwl/devkit@15.9.3
│ └─┬ @nx-tools/core@4.0.3
│   └── @nrwl/devkit@15.9.3 deduped
└─┬ @nx/cypress@16.0.3
  └─┬ @nx/devkit@16.0.3
    └── @nrwl/devkit@16.0.3
```

Thanks!

**Comment by ianldgs** [comment]
Seems like it's done in #796, but we still need a release.

**Comment by vicb** [comment]
Oh nice!
@gperdomor please close this issue when the release is out. Thanks.

**Comment by davidgarciab** [comment]
Any ETA for the release? 
I'd be very handy for my team since we're currently migrating to NX 16.
Thanks!

**Comment by gperdomor** [comment]
@vicb @davidgarciab @ianldgs Please try with `5.0.0-beta.2` and give me your feedback...

**Comment by vicb** [comment]
`5.0.0-beta.2` works great for me, thanks!

**Comment by ianldgs** [comment]
I think I was trying the 5.0.0-beta.1, which was also working. Didn't have time yet to try the beta.2.

**Comment by gperdomor** [comment]
This is fixed in v5 release 👏🏻 ... I will close this issue now
