### ISSUE TITLE
Is it possible to disable generation of image based on SHA ?

### ISSUE THREAD

**Issue by w8ze-devel** [gperdomor/nx-tools#838]
Hello,

Although it's a good practise, i sometimes need to disable the generation of the image based on the SHA.

By default, we have two images generated : one based on the branch name and another, perfectly identical, based on the SHA.

The problem is, in large projects with lots of dependencies, the registry is regularly out of space and thus leeds to extra costs.

Is there any option to only have the image based on branch name ?

Thanks

**Comment by gperdomor** [comment]
@w8ze-devel if you want to use automatic tags generation but without using `shas`, just remove the `"type=sha"` of the `metadata.tags` array in your configuration...

**Comment by w8ze-devel** [comment]
Clear, precise and lightning-fast response.

Thanks.
