### ISSUE TITLE
prisma-reset executor does not seed

### ISSUE THREAD

**Issue by maritz** [gperdomor/nx-tools#857]
When using the `prisma-reset` executor (without --skip-seed) seeding does not happen.

As far as I can tell this might not be easy to fix, since the issue is that prisma looks for the package.json in the directory you're calling it from (the workspace root) and ignores the package.json in the project root, where the seed command is defined.

Defining the seed command in the workspace root package.json would only work if I had only one project with prisma in it.

So as a workaround I have to manually call seed after reset.

**Comment by gperdomor** [comment]
Not an issue anymore
