### ISSUE TITLE
CHANGELOG content are not updated after package name changes

### ISSUE THREAD

**Issue by jchamath** [gperdomor/nx-tools#878]
After the package name changes (seemingly in 4.x.x) to `@nx-tools/container*`, the content of the CHANGELOG files are not updated. To specifically get a glance on the breaking changes, grateful if you guys can keep them up-to-date.

**Comment by gperdomor** [comment]
Version 4.x.x and 5.x.x uses GitHub releases for changelogs... For version 6.x.x I will use both methods, GitHub releases and project changelog files...
