### ISSUE TITLE
Change MIGRATE Executor

### ISSUE THREAD

**Issue by johannesschobel** [gperdomor/nx-tools#88]
Dear @gperdomor ,

just wanted to let you know, that the `migrate` command for `prisma` changed in the last versions. Find more details here on the official prisma docs: https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-flows

Furthermore, i would suggest to split the `migrations` command into multiple ones. Currently the `migrations` command adds a migration and automatically migrates the database. I would suggest to have 2 separate commands, i.e.:

`nx-tools:create-migration`, which looks like this:
```bash
prisma migrate dev --create-only --preview-feature
```

and a `nx-tools:run-migration`, which looks like this:
```bash
prisma migrate dev --preview-feature
```

All the best,
Johannes

**Comment by gperdomor** [comment]
@johannesschobel Hi, the prisma plugin is authored by @wSedlacek, we are in process of upgrade the packages to Nx 11 and @nrwl/devkit, I will assign this issue to him and hopefully he can evaluate your proposal

**Comment by wSedlacek** [comment]
I won't have a chance to look at this till this weekend. You're welcome to open a PR in the intern.
