### ISSUE TITLE
Support environment variables for all builder options

### ISSUE THREAD

**Issue by cedrickring** [gperdomor/nx-tools#89]
(This only applies to `nx-docker`)

When using `nx`, the `affected` sub-command comes in quite handy for CI environments, where only changed projects need to be built. The current nx-docker workflow requires explicit project runs when using e.g. the `INPUT_TAGS` environment variable, as all projects will be built with the same tags.

As `nx-docker` only creates a `docker`-command with the provided options in the `workspace.json`, the simplest option would be to wrap the resulting command in a `sh -c "<command>"` to substitute used environment variables in the `workspace.json`. This wouldn't change the original behavior of the builder and will only add support for environment variables.

**Comment by gperdomor** [comment]
@cedrickring try with `@nx-tools/nx-docker@beta.1`...

This commit includes your suggestion: https://github.com/gperdomor/nx-tools/commit/2b91260e8f88812713cee9f7a85e6588d41448b7

**Comment by gperdomor** [comment]
@cedrickring `beta.1` has a problem with uppercased environment variables, because returned tags are lowercased... In `beta.2` the tags is interpolated in code, the `sh -c "command"` logic is still used to handle other possible cases

**Comment by cedrickring** [comment]
Sorry for the delay. I just tested this and it works with the latest `@beta` release 👍🏽 Thanks for adding this feature 😃

**Comment by NexZhu** [comment]
@cedrickring @gperdomor  Hi I see this issue was closed long ago, but I can't figure out how to specify for example different `INPUT_CACHE_FROM` for different projects with env vars in a single `nx affected -t container` run? Thanks for helping!
