### ISSUE TITLE
publish package @nx-tools/nx-graphql-codegen

### ISSUE THREAD

**Issue by rbonillajr** [gperdomor/nx-tools#894]
Hello @gperdomor 
Could you help me by publishing the package @nx-tools/nx-graphql-codegen?

**Comment by gperdomor** [comment]
@rbonillajr for now it's published as 6.0.0-alpha.2... Please try and let me know if work as expected

**Comment by gperdomor** [comment]
@rbonillajr please move to version `1.0.0-alpha.3`, I deprecated the version `6.0.0-alpha.2` and I'm just waiting the release of Nx 19 to release the final version which will be tagged as `1.0.0`

**Comment by rbonillajr** [comment]
Hi @gperdomor, thanks for the information.

**Comment by gperdomor** [comment]
@rbonillajr version `1.0.0` is published now 😄 ... Thank you for the patience
