### ISSUE TITLE
arm64 support for gperdomor/nx-kaniko docker images

### ISSUE THREAD

**Issue by ThibaudDemay** [gperdomor/nx-tools#915]
I was looking for the source code of the docker images for nx-kaniko in particular.
But I saw issue #613 and the answers.
We use quite a lot of arm64 platform in our workflow, and we also wanted to use our arm64 resources to build our docker images via nx-kaniko use, which is not available, and not able to directly access to the source of your Dockerfile build the image directly.

Is it possible to publish a version of nx-kaniko available for arm64 platform ?

**Comment by gperdomor** [comment]
done... for nx-docker and nx-kaniko with 18.18.2 and 20.8.1
