### ISSUE TITLE
nx-container does not support nx 17

### ISSUE THREAD

**Issue by chromey** [gperdomor/nx-tools#931]
I saw that the nx peer dependency was bumped to v17 for the alpha release of nx-container v6, but wondered if there are any plans to do the same in 5.x? If not, is there any outlook when v6 will be released? Thanks a lot.

**Comment by gperdomor** [comment]
Hi @chromey, thank you for use this project... For now you can use v5.1.0 and let me know if you find any issue 🙏🏻 ...
