### ISSUE TITLE
v5.2.0 Release Notes

### ISSUE THREAD

**Issue by alexandr2110pro** [gperdomor/nx-tools#959]
Hey guys. We're using your great docker plugins in production. 

You've published the new version to npm  recently.
<img width="382" alt="Screenshot 2024-02-14 at 21 14 12" src="https://github.com/gperdomor/nx-tools/assets/2496784/546ee35f-c658-462e-8482-756c64a38a8f">

But we can't find any notes about the changes. 
We can't find any PR, [release on the github](https://github.com/gperdomor/nx-tools/releases) or git tag for 5.2.0, too.

Can you please help us find it?

**Comment by gperdomor** [comment]
@alexandr2110pro sorry for the inconvenience... it's solved now... This new release add support to Nx 18
https://github.com/gperdomor/nx-tools/releases/tag/5.2.0
